export const BACKEND_PLATFORM_ROLE_KEYWORDS = [
  "backend",
  "back-end",
  "back end",
  "백엔드",
  "server",
  "서버",
  "spring",
  "java",
  "kotlin",
  "api",
  "platform",
  "플랫폼",
  "gateway",
  "devops",
  "sre",
  "infrastructure",
  "인프라",
] as const;

export const AI_PLATFORM_ROLE_KEYWORDS = [
  "ai transformation",
  "ax",
  "ai-native",
  "ai native",
  "ai agent",
  "agent",
  "llm",
  "rag",
  "llmops",
  "mlops",
  "ai 플랫폼",
  "ai플랫폼",
  "ai 서비스",
  "ai 엔지니어",
  "프로덕트 엔지니어",
  "전사 주요 프로젝트",
  "업무 자동화",
  "개발 생산성",
  "workflow",
  "tool calling",
  "memory",
] as const;

export const NON_TARGET_ROLE_KEYWORDS = [
  "data engineer",
  "데이터 엔지니어",
  "data scientist",
  "데이터 사이언티스트",
  "ai research",
  "research engineer",
  "frontend",
  "front-end",
  "프론트",
  "android",
  "ios",
  "qa",
  "product designer",
  "ux",
  "마케터",
] as const;

export const NON_TARGET_TITLE_KEYWORDS = [
  "기획",
  "서비스 기획",
  "product manager",
  "product owner",
  "프로덕트 매니저",
  "po",
  "pm",
  "planner",
  "designer",
  "디자이너",
  "qa",
  "frontend",
  "프론트",
  "android",
  "ios",
  "data engineer",
  "데이터 엔지니어",
  "data scientist",
  "데이터 사이언티스트",
  "ai research",
  "research scientist",
  "applied scientist",
  "ai engineer (model)",
  "model researcher",
  "모델 연구",
  "cto",
  "chief technology officer",
  "tech lead",
  "server lead",
  "technical lead",
  "테크 리드",
  "기술 리드",
  "기술총괄",
  "기술 총괄",
  "manager",
  "team leader",
  "팀장",
  "조직장",
  "마케터",
  "marketing",
  "assistant",
  "어시스턴트",
  "정책",
  "e/e",
  "데이터 라벨링",
  "legal",
  "counsel",
  "법무",
  "변호사",
  "compliance manager",
  "컴플라이언스",
  "준법",
  "kyc",
  "aml",
  "privacy manager",
  "finance manager",
  "financial manager",
  "strategic finance",
  "재무",
  "accounting",
  "회계",
  "audit manager",
  "recruiting",
  "recruiter",
  "채용",
  "talent acquisition",
  "hr manager",
  "인사",
  "people partner",
  "compensation",
  "sap",
  "technical writer",
  "테크니컬 라이터",
  "strategy manager",
  "비즈니스 애널리스트",
  "business analyst",
  "operations manager",
  "운영 매니저",
  "security engineer",
  "보안 엔지니어",
] as const;

export const CONTRACT_KEYWORDS = [
  "계약직",
  "contract",
  "contractor",
  "temporary",
  "temp",
  "freelance",
  "프리랜서",
  "intern",
  "internship",
  "인턴",
  "체험형",
  "현장실습",
] as const;

export const JAVA_SPRING_KEYWORDS = [
  "java",
  "spring",
  "spring boot",
  "springboot",
  "jpa",
  "hibernate",
  "kotlin",
] as const;

export const HARD_DOMAIN_KEYWORDS = [
  "commerce",
  "커머스",
  "order",
  "주문",
  "payment",
  "payments",
  "결제",
  "정산",
  "페이",
  "bank",
  "뱅크",
  "은행",
  "loan",
  "대출",
  "credit",
  "여신",
  "수신",
  "증권",
  "금융",
  "search",
  "검색",
  "platform",
  "플랫폼",
  "kafka",
  "streaming",
  "backend",
  "백엔드",
  "server",
  "서버",
] as const;

export const AI_KEYWORDS = ["llm", "rag", "openai", "gemini", "머신러닝", "인공지능"] as const;
