import type { InterviewQuestionSourcesConfig } from "../scripts/interview-question-sources/contracts.ts";

export const interviewQuestionSources = {
  _meta: {
    purpose: "interview-practice가 질문 후보와 실무 사례를 찾을 공개 출처",
    schemaVersion: 1,
  },
  sources: [
    {
      key: "spring-framework-docs",
      title: "Spring Framework Reference",
      sourceClass: "official-reference",
      usages: ["answer-authority", "coverage-map"],
      topics: ["java-spring"],
      url: "https://docs.spring.io/spring-framework/reference/",
      adapter: "page",
    },
    {
      key: "postgresql-docs",
      title: "PostgreSQL Documentation",
      sourceClass: "official-reference",
      usages: ["answer-authority", "coverage-map"],
      topics: ["database"],
      url: "https://www.postgresql.org/docs/current/",
      adapter: "page",
    },
    {
      key: "kubernetes-docs",
      title: "Kubernetes Documentation",
      sourceClass: "official-reference",
      usages: ["answer-authority", "coverage-map"],
      topics: ["operations", "system-design"],
      url: "https://kubernetes.io/docs/concepts/",
      adapter: "page",
    },
    {
      key: "opensearch-docs",
      title: "OpenSearch Documentation",
      sourceClass: "official-reference",
      usages: ["answer-authority", "coverage-map"],
      topics: ["database", "ai-platform"],
      url: "https://docs.opensearch.org/latest/",
      adapter: "page",
    },
    {
      key: "vllm-docs",
      title: "vLLM Documentation",
      sourceClass: "official-reference",
      usages: ["answer-authority", "coverage-map"],
      topics: ["operations", "ai-platform"],
      url: "https://docs.vllm.ai/en/latest/",
      adapter: "static",
    },
    {
      key: "mcp-specification",
      title: "Model Context Protocol Specification",
      sourceClass: "official-reference",
      usages: ["answer-authority", "coverage-map"],
      topics: ["system-design", "ai-platform"],
      url: "https://modelcontextprotocol.io/specification/",
      adapter: "page",
    },
    {
      key: "anthropic-engineering",
      title: "Anthropic Engineering",
      sourceClass: "engineering-practice",
      usages: ["scenario-discovery"],
      topics: ["operations", "system-design", "ai-platform"],
      url: "https://www.anthropic.com/engineering",
      adapter: "page",
    },
    {
      key: "toss-tech",
      title: "토스 tech",
      sourceClass: "engineering-practice",
      usages: ["scenario-discovery"],
      topics: ["java-spring", "database", "operations", "system-design", "ai-platform"],
      url: "https://toss.tech/tech",
      feedUrl: "https://toss.tech/rss.xml",
      adapter: "feed",
    },
    {
      key: "woowahan-tech",
      title: "우아한형제들 기술 블로그",
      sourceClass: "engineering-practice",
      usages: ["scenario-discovery"],
      topics: ["java-spring", "database", "operations", "system-design"],
      url: "https://techblog.woowahan.com/",
      adapter: "page",
    },
    {
      key: "naver-d2",
      title: "네이버 D2",
      sourceClass: "engineering-practice",
      usages: ["scenario-discovery"],
      topics: ["java-spring", "database", "cs", "operations", "system-design", "ai-platform"],
      url: "https://d2.naver.com/home",
      feedUrl: "https://d2.naver.com/d2.atom",
      adapter: "feed",
    },
    {
      key: "line-engineering",
      title: "LINE Engineering",
      sourceClass: "engineering-practice",
      usages: ["scenario-discovery"],
      topics: ["java-spring", "database", "operations", "system-design", "ai-platform"],
      url: "https://engineering.linecorp.com/ko",
      feedUrl: "https://engineering.linecorp.com/ko/feed/",
      adapter: "feed",
    },
    {
      key: "netflix-techblog",
      title: "Netflix Technology Blog",
      sourceClass: "engineering-practice",
      usages: ["scenario-discovery"],
      topics: ["database", "operations", "system-design", "ai-platform"],
      url: "https://netflixtechblog.com/",
      feedUrl: "https://medium.com/feed/netflix-techblog",
      adapter: "feed",
    },
    {
      key: "aws-architecture-blog",
      title: "AWS Architecture Blog",
      sourceClass: "engineering-practice",
      usages: ["scenario-discovery"],
      topics: ["operations", "system-design", "ai-platform"],
      url: "https://aws.amazon.com/blogs/architecture/",
      feedUrl: "https://aws.amazon.com/blogs/architecture/feed/",
      adapter: "feed",
    },
    {
      key: "goto-conferences",
      title: "GOTO Conferences",
      sourceClass: "conference-talk",
      usages: ["scenario-discovery"],
      topics: ["java-spring", "database", "cs", "operations", "system-design", "ai-platform"],
      url: "https://www.youtube.com/@GOTO-",
      adapter: "youtube",
    },
    {
      key: "devoxx",
      title: "Devoxx",
      sourceClass: "conference-talk",
      usages: ["scenario-discovery"],
      topics: ["java-spring", "cs", "operations", "system-design", "ai-platform"],
      url: "https://www.youtube.com/@DevoxxForever",
      adapter: "youtube",
    },
    {
      key: "system-design-primer",
      title: "System Design Primer",
      sourceClass: "open-source-guide",
      usages: ["coverage-map"],
      topics: ["database", "cs", "operations", "system-design"],
      url: "https://github.com/donnemartin/system-design-primer",
      adapter: "static",
    },
    {
      key: "coding-interview-university",
      title: "Coding Interview University",
      sourceClass: "open-source-guide",
      usages: ["coverage-map"],
      topics: ["cs", "system-design"],
      url: "https://github.com/jwasham/coding-interview-university",
      adapter: "static",
    },
    {
      key: "tech-interview-handbook",
      title: "Tech Interview Handbook",
      sourceClass: "open-source-guide",
      usages: ["coverage-map"],
      topics: ["cs", "system-design", "behavioral"],
      url: "https://github.com/yangshun/tech-interview-handbook",
      adapter: "static",
    },
  ],
} satisfies InterviewQuestionSourcesConfig;
